services:
  document_store:
    build:
      context: .
    working_dir: /assistant
    command: ["python", "document_store.py"]
    volumes:
      - ./:/assistant
    env_file:
      - ../.env
    restart: unless-stopped
